document.addEventListener("DOMContentLoaded", function () {
  const imagesFolder = "../images/clients";
  const imageNames = [
    "1plus1.png",
    "2plus2.png",
    "adidas.png",
    "AFFA.png",
    "AIR.png",
    "Amako.png",
    "Amway.png",
    "APFU.png",
    "Astana.png",
    "Bacardi.png",
    "Baku-european-games.png",
    "Beeline.png",
    "BetPlanet.jpg",
    "BMS-Consulting.png",
    "Bosch.png",
    "Canal-Digital.png",
    "Canal-Plus.png",
    "Carlsberg.png",
    "Champions-League.png",
    "Chernihivske.png",
    "Coca-Cola.png",
    "CreditSuisse.png",
    "CRH.png",
    "Daewoo.png",
    "Danone.png",
    "DataGroup.png",
    "Decathlon.png",
    "Dell.png",
    "DeNovo.png",
    "DHL.png",
    "Donbassenergo.png",
    "dspartners.jpg",
    "Dynamo-Brest.png",
    "Dynamo-Kyiv.png",
    "ELKO.png",
    "epam.png",
    "Epicentr.png",
    "EURO-2012.png",
    "Europa-League.png",
    "Favbet.png",
    "FC LB.png",
    "FC-Dnipro-Cherkasy.png",
    "FC-Energy-Lviv.png",
    "FC-Hyrnyk-Sport.png",
    "FC-Metalist-Kharkiv.png",
    "FC-Metalurg.png",
    "FC-Olimpik-Donetsk.png",
    "FM-Group.png",
    "Football-Academy-Zoloche.png",
    "Football1-2-3.png",
    "Fozzy-Group.png",
    "Gillete.png",
    "giz.png",
    "Global-Spirits.png",
    "Grill-do-Brasil.png",
    "Gymnasium-Aplus.png",
    "Heineken.png",
    "Hisense.png",
    "Hyundai.png",
    "ICTV.png",
    "IDS.png",
    "Intellias.png",
    "Interpipe.png",
    "Intersport.png",
    "Intertop.png",
    "JTI.png",
    "K1.png",
    "Karavan-outlet.png",
    "KIA.png",
    "Kovalska.png",
    "Lambre.png",
    "Lego.png",
    "lifecell.png",
    "Lvivoblenergo.png",
    "M1.png",
    "Mastercard.png",
    "McDonalds.png",
    "Meest.png",
    "Megapolis.png",
    "Metinvest.png",
    "MG.png",
    "Microsoft.png",
    "Miratech.png",
    "MTS.png",
    "MTV.png",
    "Nike.png",
    "Nissan.png",
    "NLO-TV.png",
    "NOK-Ukraine.png",
    "NonStop-Energy.png",
    "Novo Nordisk.png",
    "Novyi-kanal.png",
    "NSC-Olimpiyskiy.png",
    "OBI.png",
    "Okko.png",
    "Olkom.png",
    "Olymp.png",
    "Opet.png",
    "OTIS.png",
    "PariMatch.png",
    "Pepsi.png",
    "Pepsico.png",
    "Persha-pryvatna-brovarnya.png",
    "PlayStation.png",
    "Premiere-Palace-Hotel.png",
    "Puma.png",
    "Qatar-Airways.png",
    "Qatar-FanZone.png",
    "RedBull.png",
    "save_ukraine.png",
    "Scania.png",
    "Shakhtar-Donetsk.png",
    "Sharp.png",
    "SkySports.png",
    "Sport Life.png",
    "StarBurger.png",
    "Stargorod.png",
    "STB.png",
    "Street Culture.png",
    "Studio-Moderna.png",
    "TET.png",
    "TetraPak.png",
    "TGI-Fridays.png",
    "TransKreditBank.png",
    "UA-TV.png",
    "UAE-FA.png",
    "UAF.png",
    "udp.png",
    "UEFA.png",
    "UkrBud.png",
    "Ukrsibbank.png",
    "Ulichnaya Eda.png",
    "UNICEF.png",
    "VideoZhara.png",
    "Volia.png",
    "Zeppelin-CAT.png",
    "Zoloche-School.png",
  ];

  const clientsGrid = document.querySelector(".clients-grid");

  imageNames.forEach((name) => {
    const img = document.createElement("img");
    img.src = `${imagesFolder}/${name}`;
    img.alt = name.replace(".png", "");
    img.classList.add("logo");

    clientsGrid.appendChild(img);
  });
});
